tpt:
  func: escalation::get_three_plus_three
  args:
    allow_deescalate: TRUE
    num_doses: 5

  
crm:
  func: escalation::get_dfcrm
  args:
    skeleton: [0.02,0.08,0.20,0.35,0.6]
    target: 0.55
    scale: 0.64
    num_doses: 4

